name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:alpine3.18
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - .:/home/rust/src
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        cd /home/rust/src/
        ls -lah
        apk update
        apk add --no-cache musl-dev openssl-dev openssl-libs-static fuse3-static fuse3-dev fuse3
        OPENSSL_STATIC=1 cargo build --release
        ls -lah ./target/release/
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: onedrive-fuse-musl
        path: target/release/onedrive-fuse
